export const alpha3code = {
  ABW: 'Aruba',
  AFG: 'Afghanistan',
  AGO: 'Angola',
  AIA: 'Anguilla',
  ALA: 'Åland Islands',
  ALB: 'Albania',
  AND: 'Andorra',
  ARE: 'United Arab Emirates',
  ARG: 'Argentina',
  ARM: 'Armenia',
  ASM: 'American Samoa',
  ATA: 'Antarctica',
  ATF: 'French Southern Territories',
  ATG: 'Antigua and Barbuda',
  AUS: 'Australia',
  AUT: 'Austria',
  AZE: 'Azerbaijan',
  BDI: 'Burundi',
  BEL: 'Belgium',
  BEN: 'Benin',
  BES: 'Bonaire, Sint Eustatius and Saba',
  BFA: 'Burkina Faso',
  BGD: 'Bangladesh',
  BGR: 'Bulgaria',
  BHR: 'Bahrain',
  BHS: 'Bahamas',
  BIH: 'Bosnia and Herzegovina',
  BLM: 'Saint Barthélemy',
  BLR: 'Belarus',
  BLZ: 'Belize',
  BMU: 'Bermuda',
  BOL: 'Bolivia (Plurinational State of)',
  BRA: 'Brazil',
  BRB: 'Barbados',
  BRN: 'Brunei Darussalam',
  BTN: 'Bhutan',
  BVT: 'Bouvet Island',
  BWA: 'Botswana',
  CAF: 'Central African Republic',
  CAN: 'Canada',
  CCK: 'Cocos (Keeling) Islands',
  CHE: 'Switzerland',
  CHL: 'Chile',
  CHN: 'China',
  CIV: "Côte d'Ivoire",
  CMR: 'Cameroon',
  COD: 'Congo (Democratic Republic of the)',
  COG: 'Congo',
  COK: 'Cook Islands',
  COL: 'Colombia',
  COM: 'Comoros',
  CPV: 'Cabo Verde',
  CRI: 'Costa Rica',
  CUB: 'Cuba',
  CUW: 'Curaçao',
  CXR: 'Christmas Island',
  CYM: 'Cayman Islands',
  CYP: 'Cyprus',
  CZE: 'Czech Republic',
  DEU: 'Germany',
  DJI: 'Djibouti',
  DMA: 'Dominica',
  DNK: 'Denmark',
  DOM: 'Dominican Republic',
  DZA: 'Algeria',
  ECU: 'Ecuador',
  EGY: 'Egypt',
  ERI: 'Eritrea',
  ESH: 'Western Sahara',
  ESP: 'Spain',
  EST: 'Estonia',
  ETH: 'Ethiopia',
  FIN: 'Finland',
  FJI: 'Fiji',
  FLK: 'Falkland Islands (Malvinas)',
  FRA: 'France',
  FRO: 'Faroe Islands',
  FSM: 'Micronesia (Federated States of)',
  GAB: 'Gabon',
  GBR: 'United Kingdom of Great Britain and Northern Ireland',
  GEO: 'Georgia',
  GGY: 'Guernsey',
  GHA: 'Ghana',
  GIB: 'Gibraltar',
  GIN: 'Guinea',
  GLP: 'Guadeloupe',
  GMB: 'Gambia',
  GNB: 'Guinea-Bissau',
  GNQ: 'Equatorial Guinea',
  GRC: 'Greece',
  GRD: 'Grenada',
  GRL: 'Greenland',
  GTM: 'Guatemala',
  GUF: 'French Guiana',
  GUM: 'Guam',
  GUY: 'Guyana',
  HKG: 'Hong Kong',
  HMD: 'Heard Island and McDonald Islands',
  HND: 'Honduras',
  HRV: 'Croatia',
  HTI: 'Haiti',
  HUN: 'Hungary',
  IDN: 'Indonesia',
  IMN: 'Isle of Man',
  IND: 'India',
  IOT: 'British Indian Ocean Territory',
  IRL: 'Ireland',
  IRN: 'Iran (Islamic Republic of)',
  IRQ: 'Iraq',
  ISL: 'Iceland',
  ISR: 'Israel',
  ITA: 'Italy',
  JAM: 'Jamaica',
  JEY: 'Jersey',
  JOR: 'Jordan',
  JPN: 'Japan',
  KAZ: 'Kazakhstan',
  KEN: 'Kenya',
  KGZ: 'Kyrgyzstan',
  KHM: 'Cambodia',
  KIR: 'Kiribati',
  KNA: 'Saint Kitts and Nevis',
  KOR: 'Korea (Republic of)',
  KOS: 'Republic of Kosovo',
  KWT: 'Kuwait',
  LAO: "Lao People's Democratic Republic",
  LBN: 'Lebanon',
  LBR: 'Liberia',
  LBY: 'Libya',
  LCA: 'Saint Lucia',
  LIE: 'Liechtenstein',
  LKA: 'Sri Lanka',
  LSO: 'Lesotho',
  LTU: 'Lithuania',
  LUX: 'Luxembourg',
  LVA: 'Latvia',
  MAC: 'Macao',
  MAF: 'Saint Martin (French part)',
  MAR: 'Morocco',
  MCO: 'Monaco',
  MDA: 'Moldova (Republic of)',
  MDG: 'Madagascar',
  MDV: 'Maldives',
  MEX: 'Mexico',
  MHL: 'Marshall Islands',
  MKD: 'Macedonia (the former Yugoslav Republic of)',
  MLI: 'Mali',
  MLT: 'Malta',
  MMR: 'Myanmar',
  MNE: 'Montenegro',
  MNG: 'Mongolia',
  MNP: 'Northern Mariana Islands',
  MOZ: 'Mozambique',
  MRT: 'Mauritania',
  MSR: 'Montserrat',
  MTQ: 'Martinique',
  MUS: 'Mauritius',
  MWI: 'Malawi',
  MYS: 'Malaysia',
  MYT: 'Mayotte',
  NAM: 'Namibia',
  NCL: 'New Caledonia',
  NER: 'Niger',
  NFK: 'Norfolk Island',
  NGA: 'Nigeria',
  NIC: 'Nicaragua',
  NIU: 'Niue',
  NLD: 'Netherlands',
  NOR: 'Norway',
  NPL: 'Nepal',
  NRU: 'Nauru',
  NZL: 'New Zealand',
  OMN: 'Oman',
  PAK: 'Pakistan',
  PAN: 'Panama',
  PCN: 'Pitcairn',
  PER: 'Peru',
  PHL: 'Philippines',
  PLW: 'Palau',
  PNG: 'Papua New Guinea',
  POL: 'Poland',
  PRI: 'Puerto Rico',
  PRK: "Korea (Democratic People's Republic of)",
  PRT: 'Portugal',
  PRY: 'Paraguay',
  PSE: 'Palestine, State of',
  PYF: 'French Polynesia',
  QAT: 'Qatar',
  REU: 'Réunion',
  ROU: 'Romania',
  RUS: 'Russian Federation',
  RWA: 'Rwanda',
  SAU: 'Saudi Arabia',
  SDN: 'Sudan',
  SEN: 'Senegal',
  SGP: 'Singapore',
  SGS: 'South Georgia and the South Sandwich Islands',
  SHN: 'Saint Helena, Ascension and Tristan da Cunha',
  SJM: 'Svalbard and Jan Mayen',
  SLB: 'Solomon Islands',
  SLE: 'Sierra Leone',
  SLV: 'El Salvador',
  SMR: 'San Marino',
  SOM: 'Somalia',
  SPM: 'Saint Pierre and Miquelon',
  SRB: 'Serbia',
  SSD: 'South Sudan',
  STP: 'Sao Tome and Principe',
  SUR: 'Suriname',
  SVK: 'Slovakia',
  SVN: 'Slovenia',
  SWE: 'Sweden',
  SWZ: 'Swaziland',
  SXM: 'Sint Maarten (Dutch part)',
  SYC: 'Seychelles',
  SYR: 'Syrian Arab Republic',
  TCA: 'Turks and Caicos Islands',
  TCD: 'Chad',
  TGO: 'Togo',
  THA: 'Thailand',
  TJK: 'Tajikistan',
  TKL: 'Tokelau',
  TKM: 'Turkmenistan',
  TLS: 'Timor-Leste',
  TON: 'Tonga',
  TTO: 'Trinidad and Tobago',
  TUN: 'Tunisia',
  TUR: 'Turkey',
  TUV: 'Tuvalu',
  TWN: 'Taiwan',
  TZA: 'Tanzania, United Republic of',
  UGA: 'Uganda',
  UKR: 'Ukraine',
  UMI: 'United States Minor Outlying Islands',
  URY: 'Uruguay',
  USA: 'United States of America',
  UZB: 'Uzbekistan',
  VAT: 'Holy See',
  VCT: 'Saint Vincent and the Grenadines',
  VEN: 'Venezuela (Bolivarian Republic of)',
  VGB: 'Virgin Islands (British)',
  VIR: 'Virgin Islands (U.S.)',
  VNM: 'Viet Nam',
  VUT: 'Vanuatu',
  WLF: 'Wallis and Futuna',
  WSM: 'Samoa',
  YEM: 'Yemen',
  ZAF: 'South Africa',
  ZMB: 'Zambia',
  ZWE: 'Zimbabwe',
};

export const flagCode = {
  ABW: '../assets/images/png/abw.png',
  AFG: '../assets/images/png/afg.png',
  AGO: '../assets/images/png/ago.png',
  AIA: '../assets/images/png/aia.png',
  ALA: '../assets/images/png/ala.png',
  ALB: '../assets/images/png/alb.png',
  AND: '../assets/images/png/and.png',
  ARE: '../assets/images/png/are.png',
  ARG: '../assets/images/png/arg.png',
  ARM: '../assets/images/png/arm.png',
  ASM: '../assets/images/png/asm.png',
  ATA: '../assets/images/png/ata.png',
  ATF: '../assets/images/png/atf.png',
  ATG: '../assets/images/png/atg.png',
  AUS: '../assets/images/png/aus.png',
  AUT: '../assets/images/png/aut.png',
  AZE: '../assets/images/png/aze.png',
  BDI: '../assets/images/png/bdi.png',
  BEL: '../assets/images/png/bel.png',
  BEN: '../assets/images/png/ben.png',
  BES: '../assets/images/png/bes.png',
  BFA: '../assets/images/png/bfa.png',
  BGD: '../assets/images/png/bgd.png',
  BGR: '../assets/images/png/bgr.png',
  BHR: '../assets/images/png/bhr.png',
  BHS: '../assets/images/png/bhs.png',
  BIH: '../assets/images/png/bih.png',
  BLM: '../assets/images/png/blm.png',
  BLR: '../assets/images/png/blr.png',
  BLZ: '../assets/images/png/blz.png',
  BMU: '../assets/images/png/bmu.png',
  BOL: '../assets/images/png/bol.png',
  BRA: '../assets/images/png/bra.png',
  BRB: '../assets/images/png/brb.png',
  BRN: '../assets/images/png/brn.png',
  BTN: '../assets/images/png/btn.png',
  BVT: '../assets/images/png/bvt.png',
  BWA: '../assets/images/png/bwa.png',
  CAF: '../assets/images/png/caf.png',
  CAN: '../assets/images/png/can.png',
  CCK: '../assets/images/png/cck.png',
  CHE: '../assets/images/png/che.png',
  CHL: '../assets/images/png/chl.png',
  CHN: '../assets/images/png/chn.png',
  CIV: '../assets/images/png/civ.png',
  CMR: '../assets/images/png/cmr.png',
  COD: '../assets/images/png/cod.png',
  COG: '../assets/images/png/cog.png',
  COK: '../assets/images/png/cok.png',
  COL: '../assets/images/png/col.png',
  COM: '../assets/images/png/com.png',
  CPV: '../assets/images/png/cpv.png',
  CRI: '../assets/images/png/cri.png',
  CUB: '../assets/images/png/cub.png',
  CUW: '../assets/images/png/cuw.png',
  CXR: '../assets/images/png/cxr.png',
  CYM: '../assets/images/png/cym.png',
  CYP: '../assets/images/png/cyp.png',
  CZE: '../assets/images/png/cze.png',
  DEU: '../assets/images/png/deu.png',
  DJI: '../assets/images/png/dji.png',
  DMA: '../assets/images/png/dma.png',
  DNK: '../assets/images/png/dnk.png',
  DOM: '../assets/images/png/dom.png',
  DZA: '../assets/images/png/dza.png',
  ECU: '../assets/images/png/ecu.png',
  EGY: '../assets/images/png/egy.png',
  ERI: '../assets/images/png/eri.png',
  ESH: '../assets/images/png/esh.png',
  ESP: '../assets/images/png/esp.png',
  EST: '../assets/images/png/est.png',
  ETH: '../assets/images/png/eth.png',
  FIN: '../assets/images/png/fin.png',
  FJI: '../assets/images/png/fji.png',
  FLK: '../assets/images/png/flk.png',
  FRA: '../assets/images/png/fra.png',
  FRO: '../assets/images/png/fro.png',
  FSM: '../assets/images/png/fsm.png',
  GAB: '../assets/images/png/gab.png',
  GBR: '../assets/images/png/gbr.png',
  GEO: '../assets/images/png/geo.png',
  GGY: '../assets/images/png/ggy.png',
  GHA: '../assets/images/png/gha.png',
  GIB: '../assets/images/png/gib.png',
  GIN: '../assets/images/png/gin.png',
  GLP: '../assets/images/png/glp.png',
  GMB: '../assets/images/png/gmb.png',
  GNB: '../assets/images/png/gnb.png',
  GNQ: '../assets/images/png/gnq.png',
  GRC: '../assets/images/png/grc.png',
  GRD: '../assets/images/png/grd.png',
  GRL: '../assets/images/png/grl.png',
  GTM: '../assets/images/png/gtm.png',
  GUF: '../assets/images/png/guf.png',
  GUM: '../assets/images/png/gum.png',
  GUY: '../assets/images/png/guy.png',
  HKG: '../assets/images/png/hkg.png',
  HMD: '../assets/images/png/hmd.png',
  HND: '../assets/images/png/hnd.png',
  HRV: '../assets/images/png/hrv.png',
  HTI: '../assets/images/png/hti.png',
  HUN: '../assets/images/png/hun.png',
  IDN: '../assets/images/png/idn.png',
  IMN: '../assets/images/png/imn.png',
  IND: '../assets/images/png/ind.png',
  IOT: '../assets/images/png/iot.png',
  IRL: '../assets/images/png/irl.png',
  IRN: '../assets/images/png/irn.png',
  IRQ: '../assets/images/png/irq.png',
  ISL: '../assets/images/png/isl.png',
  ISR: '../assets/images/png/isr.png',
  ITA: '../assets/images/png/ita.png',
  JAM: '../assets/images/png/jam.png',
  JEY: '../assets/images/png/jey.png',
  JOR: '../assets/images/png/jor.png',
  JPN: '../assets/images/png/jpn.png',
  KAZ: '../assets/images/png/kaz.png',
  KEN: '../assets/images/png/ken.png',
  KGZ: '../assets/images/png/kgz.png',
  KHM: '../assets/images/png/khm.png',
  KIR: '../assets/images/png/kir.png',
  KNA: '../assets/images/png/kna.png',
  KOR: '../assets/images/png/kor.png',
  KOS: '../assets/images/png/kos.png',
  KWT: '../assets/images/png/kwt.png',
  LAO: '../assets/images/png/lao.png',
  LBN: '../assets/images/png/lbn.png',
  LBR: '../assets/images/png/lbr.png',
  LBY: '../assets/images/png/lby.png',
  LCA: '../assets/images/png/lca.png',
  LIE: '../assets/images/png/lie.png',
  LKA: '../assets/images/png/lka.png',
  LSO: '../assets/images/png/lso.png',
  LTU: '../assets/images/png/ltu.png',
  LUX: '../assets/images/png/lux.png',
  LVA: '../assets/images/png/lva.png',
  MAC: '../assets/images/png/mac.png',
  MAF: '../assets/images/png/maf.png',
  MAR: '../assets/images/png/mar.png',
  MCO: '../assets/images/png/mco.png',
  MDA: '../assets/images/png/mda.png',
  MDG: '../assets/images/png/mdg.png',
  MDV: '../assets/images/png/mdv.png',
  MEX: '../assets/images/png/mex.png',
  MHL: '../assets/images/png/mhl.png',
  MKD: '../assets/images/png/mkd.png',
  MLI: '../assets/images/png/mli.png',
  MLT: '../assets/images/png/mlt.png',
  MMR: '../assets/images/png/mmr.png',
  MNE: '../assets/images/png/mne.png',
  MNG: '../assets/images/png/mng.png',
  MNP: '../assets/images/png/mnp.png',
  MOZ: '../assets/images/png/moz.png',
  MRT: '../assets/images/png/mrt.png',
  MSR: '../assets/images/png/msr.png',
  MTQ: '../assets/images/png/mtq.png',
  MUS: '../assets/images/png/mus.png',
  MWI: '../assets/images/png/mwi.png',
  MYS: '../assets/images/png/mys.png',
  MYT: '../assets/images/png/myt.png',
  NAM: '../assets/images/png/nam.png',
  NCL: '../assets/images/png/ncl.png',
  NER: '../assets/images/png/ner.png',
  NFK: '../assets/images/png/nfk.png',
  NGA: '../assets/images/png/nga.png',
  NIC: '../assets/images/png/nic.png',
  NIU: '../assets/images/png/niu.png',
  NLD: '../assets/images/png/nld.png',
  NOR: '../assets/images/png/nor.png',
  NPL: '../assets/images/png/npl.png',
  NRU: '../assets/images/png/nru.png',
  NZL: '../assets/images/png/nzl.png',
  OMN: '../assets/images/png/omn.png',
  PAK: '../assets/images/png/pak.png',
  PAN: '../assets/images/png/pan.png',
  PCN: '../assets/images/png/pcn.png',
  PER: '../assets/images/png/per.png',
  PHL: '../assets/images/png/phl.png',
  PLW: '../assets/images/png/plw.png',
  PNG: '../assets/images/png/png.png',
  POL: '../assets/images/png/pol.png',
  PRI: '../assets/images/png/pri.png',
  PRK: '../assets/images/png/prk.png',
  PRT: '../assets/images/png/prt.png',
  PRY: '../assets/images/png/pry.png',
  PSE: '../assets/images/png/pse.png',
  PYF: '../assets/images/png/pyf.png',
  QAT: '../assets/images/png/qat.png',
  REU: '../assets/images/png/reu.png',
  ROU: '../assets/images/png/rou.png',
  RUS: '../assets/images/png/rus.png',
  RWA: '../assets/images/png/rwa.png',
  SAU: '../assets/images/png/sau.png',
  SDN: '../assets/images/png/sdn.png',
  SEN: '../assets/images/png/sen.png',
  SGP: '../assets/images/png/sgp.png',
  SGS: '../assets/images/png/sgs.png',
  SHN: '../assets/images/png/shn.png',
  SJM: '../assets/images/png/sjm.png',
  SLB: '../assets/images/png/slb.png',
  SLE: '../assets/images/png/sle.png',
  SLV: '../assets/images/png/slv.png',
  SMR: '../assets/images/png/smr.png',
  SOM: '../assets/images/png/som.png',
  SPM: '../assets/images/png/spm.png',
  SRB: '../assets/images/png/srb.png',
  SSD: '../assets/images/png/ssd.png',
  STP: '../assets/images/png/stp.png',
  SUR: '../assets/images/png/sur.png',
  SVK: '../assets/images/png/svk.png',
  SVN: '../assets/images/png/svn.png',
  SWE: '../assets/images/png/swe.png',
  SWZ: '../assets/images/png/swz.png',
  SXM: '../assets/images/png/sxm.png',
  SYC: '../assets/images/png/syc.png',
  SYR: '../assets/images/png/syr.png',
  TCA: '../assets/images/png/tca.png',
  TCD: '../assets/images/png/tcd.png',
  TGO: '../assets/images/png/tgo.png',
  THA: '../assets/images/png/tha.png',
  TJK: '../assets/images/png/tjk.png',
  TKL: '../assets/images/png/tkl.png',
  TKM: '../assets/images/png/tkm.png',
  TLS: '../assets/images/png/tls.png',
  TON: '../assets/images/png/ton.png',
  TTO: '../assets/images/png/tto.png',
  TUN: '../assets/images/png/tun.png',
  TUR: '../assets/images/png/tur.png',
  TUV: '../assets/images/png/tuv.png',
  TWN: '../assets/images/png/twn.png',
  TZA: '../assets/images/png/tza.png',
  UGA: '../assets/images/png/uga.png',
  UKR: '../assets/images/png/ukr.png',
  UMI: '../assets/images/png/umi.png',
  URY: '../assets/images/png/ury.png',
  USA: '../assets/images/png/usa.png',
  UZB: '../assets/images/png/uzb.png',
  VAT: '../assets/images/png/vat.png',
  VCT: '../assets/images/png/vct.png',
  VEN: '../assets/images/png/ven.png',
  VGB: '../assets/images/png/vgb.png',
  VIR: '../assets/images/png/vir.png',
  VNM: '../assets/images/png/vnm.png',
  VUT: '../assets/images/png/vut.png',
  WLF: '../assets/images/png/wlf.png',
  WSM: '../assets/images/png/wsm.png',
  YEM: '../assets/images/png/yem.png',
  ZAF: '../assets/images/png/zaf.png',
  ZMB: '../assets/images/png/zmb.png',
  ZWE: '../assets/images/png/zwe.png',
};
